export const applications = [
  {
    jobId: '11111111-1111-4111-8111-111111111111',
    logo: 'S',
    title: 'Senior UI Designer',
    company: 'VinGroup - Hanoi',
    status: 'Interview Stage',
    updated: 'Updated 2 hours ago',
    progress: 76,
  },
  {
    jobId: '22222222-2222-4222-8222-222222222222',
    logo: 'F',
    title: 'Frontend Architect',
    company: 'FPT Software - HCMC',
    status: 'Applied',
    updated: 'Updated 1 day ago',
    progress: 34,
  },
  {
    jobId: '33333333-3333-4333-8333-333333333333',
    logo: 'M',
    title: 'Product Designer',
    company: 'MoMo - Remote',
    status: 'Rejected',
    updated: 'Updated 3 days ago',
    progress: 92,
  },
]

export const candidateNavItems = [
  { label: 'Dashboard', icon: 'fa-table-cells-large', path: '/candidate' },
  { label: 'My Applications', icon: 'fa-briefcase' },
  { label: 'Interviews', icon: 'fa-calendar-check' },
  { label: 'AI Insights', icon: 'fa-lightbulb' },
  { label: 'Companies', icon: 'fa-building', path: '/candidate/companies' },
  { label: 'Profile Settings', icon: 'fa-gear' },
]

export const candidateCompanies = [
  {
    id: 'technova',
    name: 'TechNova Labs',
    description: 'Senior Enterprise Account Manager',
    logo: 'T',
    industry: 'Technology, Information and Internet',
    size: '201 - 500 employees',
    location: 'San Francisco, CA',
    country: 'United States',
    openings: 12,
    color: 'blue',
  },
  {
    id: 'greenleaf',
    name: 'Canifa Digital',
    description: 'Customer Data Platform Specialist',
    logo: 'CANIFA',
    industry: 'Retail Technology',
    size: '51 - 200 employees',
    location: 'New York, NY',
    country: 'United States',
    openings: 5,
    color: 'red',
  },
  {
    id: 'healthplus',
    name: 'OrthoCare Group',
    description: 'Accounting Specialist',
    logo: 'ORTHO',
    industry: 'Healthcare Services',
    size: '501 - 1000 employees',
    location: 'Boston, MA',
    country: 'United States',
    openings: 8,
    color: 'white',
  },
  {
    id: 'shopeasy',
    name: 'IGMA Consulting',
    description: 'Sales Executive',
    logo: 'IGMA',
    industry: 'Business Consulting',
    size: '201 - 500 employees',
    location: 'Chicago, IL',
    country: 'United States',
    openings: 7,
    color: 'yellow',
  },
  {
    id: 'fincore',
    name: 'GoldCare Manufacturing',
    description: 'Content Creator',
    logo: 'GC',
    industry: 'Manufacturing',
    size: '1001+ employees',
    location: 'Seattle, WA',
    country: 'United States',
    openings: 15,
    color: 'gold',
  },
  {
    id: 'pixelplay',
    name: 'Corefronic Systems',
    description: 'Bilingual Operations Coordinator',
    logo: 'Corefronic',
    industry: 'Industrial Technology',
    size: '51 - 200 employees',
    location: 'Austin, TX',
    country: 'United States',
    openings: 4,
    color: 'white',
  },
  {
    id: 'seico',
    name: 'Seico Steel',
    description: 'B2B Sales Manager',
    logo: 'SEICO',
    industry: 'Construction Materials',
    size: '201 - 500 employees',
    location: 'Denver, CO',
    country: 'United States',
    openings: 9,
    color: 'blue',
  },
  {
    id: 'hailong',
    name: 'HaiLong Pharma',
    description: 'Digital Marketing Specialist',
    logo: 'HL',
    industry: 'Pharmaceuticals',
    size: '51 - 200 employees',
    location: 'Portland, OR',
    country: 'United States',
    openings: 6,
    color: 'green',
  },
  {
    id: 'halla',
    name: 'Halla Electronics',
    description: 'Korean-English Interpreter',
    logo: 'HEV',
    industry: 'Electronics Manufacturing',
    size: '1001+ employees',
    location: 'Dallas, TX',
    country: 'United States',
    openings: 11,
    color: 'white',
  },
]

export const candidateCompanyJobs = [
  {
    id: 'senior-frontend-engineer',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    employmentType: 'Part-time',
    salaryRange: '$1,000 - $1,500',
    location: 'San Francisco, CA (Hybrid)',
    workType: 'Full-time',
  },
  {
    id: 'product-manager',
    title: 'Product Manager',
    department: 'Product',
    employmentType: 'Part-time',
    salaryRange: '$1,000 - $1,500',
    location: 'Remote (US)',
    workType: 'Full-time',
  },
  {
    id: 'ux-designer',
    title: 'UX Designer',
    department: 'Design',
    employmentType: 'Part-time',
    salaryRange: '$1,000 - $1,500',
    location: 'New York, NY',
    workType: 'Contract',
  },
  {
    id: 'backend-developer-1',
    title: 'Backend Developer',
    department: 'Engineering',
    employmentType: 'Part-time',
    salaryRange: '$1,000 - $1,500',
    location: 'Remote',
    workType: 'Full-time',
  },
  {
    id: 'backend-developer-2',
    title: 'Backend Developer',
    department: 'Engineering',
    employmentType: 'Part-time',
    salaryRange: '$1,000 - $1,500',
    location: 'Remote',
    workType: 'Full-time',
  },
  {
    id: 'backend-developer-3',
    title: 'Backend Developer',
    department: 'Engineering',
    employmentType: 'Part-time',
    salaryRange: '$1,000 - $1,500',
    location: 'Remote',
    workType: 'Full-time',
  },
]
